### ISSUE TITLE
Sugestão: Retornar Erros como Objetos Serializáveis no ValidatorPipe

### ISSUE THREAD

**Issue by https-richardy** [dev-Raffa/boilerplate-nestjs#1]
Atualmente, o decorador ValidatorPipe, localizado no arquivo [validatorPipe.decorator.ts](https://github.com/dev-Raffa/BlogCMS-Api/blob/master/src/utils/decorators/validatorPipe/validatorPipe.decorator.ts), retorna os erros como uma string na propriedade message do objeto de erro. Esta abordagem dificulta a manipulação e exibição dos erros do lado do cliente.

Sugiro que os erros sejam retornados como um objeto, o que permitirá uma serialização mais eficiente e uma manipulação mais fácil do lado do cliente. Isso possibilitaria que os clientes recebam os erros como um JSON e facilmente os processem em sua interface do usuário.

## Proposta:

```typescript
throwError(errors: any[]) {
  throw new HttpException(
    {
      message: 'Validation failed',
      errors: errors, // Alteração proposta
      error: 'Bad Request',
      statusCode: HttpStatus.BAD_REQUEST
    },
    HttpStatus.BAD_REQUEST
  );
}
```

Com essa alteração, os erros serão retornados em um formato que pode ser facilmente serializado e manipulado pelo cliente.

---

Nessa abordagem proposta os erros são retornados como um objeto serializável, em um formato estruturado, como um JSON, que inclui detalhes sobre cada erro, como o campo afetado e uma mensagem descritiva.

```json
{
  "message": "Validation failed",
  "errors": [
    {
      "field": "password",
      "message": "A senha deve conter no mínimo 8 caracteres"
    }
  ],
  "error": "Bad Request",
  "statusCode": 400
}
```

**Comment by dev-Raffa** [comment]
@https-richardy gostaria de agradecer pela sua sugestão e informar que ela foi aceita e implementada. 
Além de aperfeiçoar-mos o retorno das exceptions lançadas pelo ValidatorPipe. Incluímos a possibilidade de personalização das mensagens de erros do decorator de validação. Em breve atualizaremos a documentação do projeto.
